### ISSUE TITLE
Audio recording unresponsive, user unexpectedly logged out 4xx-5xx Error handling

### ISSUE THREAD

**Issue by surajsahani** [navgurukul/oscar_ai_transcription#9]
https://github.com/user-attachments/assets/979a4920-0865-41c6-a41c-93edc271485c

**Comment by surajsahani** [comment]
Details - https://navgurukul.slack.com/archives/C07JFP271J5/p1732025168467279

**Comment by Jayshri15** [comment]
It's resolved

**Comment by shalini8979** [comment]
Not testable by QA fixed by dev.

**Comment by surajsahani** [comment]
Not fixed. - backend issue reference - https://github.com/navgurukul/oscar-be/issues/36
